In [2]:
import pandas as pd

In [34]:
#STEP 1 estrerre synapse_id 
df_ID_patient= pd.read_csv('/mnt/cold1/snaketree/prj/scRNA/dataset/Scanpy_prova/Progressive_plasticity_during_colorectal_cancer_metastasis/2023-07-12062C-Supplementary_Table_1 - b.tsv',header=0,index_col=0, sep='\t')
df_ID_patient=df_ID_patient.reset_index()
print(df_ID_patient.head())

  Lab ID  H5AD ID HTAN Patient ID MSK Patient ID HTAN Biospecimen ID  \
0   KG11N   KG11N       HTA8_6001     MSKCRC0153    HTA8_6001_001101
1   KG11P   KG11P       HTA8_6001     MSKCRC0153    HTA8_6001_002101
2  KG11Li   KG11M       HTA8_6001     MSKCRC0153    HTA8_6001_003101
3   KG20N   KG20N       HTA8_6002     MSKCRC0154    HTA8_6002_001101
4   KG20P   KG20P       HTA8_6002     MSKCRC0154    HTA8_6002_002101

  Manuscript
0          Y
1          Y
2          Y
3          Y
4          Y

In [30]:
df_file_patient = pd.read_csv('table_data.tsv', sep='\t')

print(df_file_patient.head())

                                            Filename Atlas Name  Publications  \
0  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...   HTAN MSK           NaN
1  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...   HTAN MSK           NaN
2  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...   HTAN MSK           NaN
3  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...   HTAN MSK           NaN
4  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...   HTAN MSK           NaN

        Biospecimen      Assay    Level          Organ  Treatment  \
0  HTA8_6001_001101  scRNA-seq  Level 3  Sigmoid colon        NaN
1  HTA8_6001_001101  scRNA-seq  Level 3  Sigmoid colon        NaN
2  HTA8_6001_001101  scRNA-seq  Level 3  Sigmoid colon        NaN
3  HTA8_6001_001101  scRNA-seq  Level 3  Sigmoid colon        NaN
4  HTA8_6001_002101  scRNA-seq  Level 3  Sigmoid colon        NaN

            Diagnosis Data Access  ... Cell Barcode Offset Empty Well Barcode  \
0  Adenocarcinoma NOS     Synapse  ...                 NaN                NaN
1  Adenocarcinoma NOS     Synapse  ...                 NaN                NaN
2  Adenocarcinoma NOS     Synapse  ...                 NaN                NaN
3  Adenocarcinoma NOS     Synapse  ...                 NaN                NaN
4  Adenocarcinoma NOS     Synapse  ...                 NaN                NaN

  Feature Reference Id Median UM Isper Cell Number UMI Barcode Length  \
0                  NaN                         NaN                NaN
1                  NaN                         NaN                NaN
2                  NaN                         NaN                NaN
3                  NaN                         NaN                NaN
4                  NaN                         NaN                NaN

  UMI Barcode Offset Valid Barcodes Cell Number  Parent Biospecimen ID  \
0                NaN                        NaN                    NaN
1                NaN                        NaN                    NaN
2                NaN                        NaN                    NaN
3                NaN                        NaN                    NaN
4                NaN                        NaN                    NaN

   Metadata  View
0   Details   NaN
1   Details   NaN
2   Details   NaN
3   Details   NaN
4   Details   NaN

[5 rows x 69 columns]

In [37]:
df_reduce_ID_patient = df_ID_patient[['Lab ID ', 'H5AD ID', 'HTAN Patient ID','HTAN Biospecimen ID']]

df_reduce_ID_patient

     Lab ID    H5AD ID HTAN Patient ID HTAN Biospecimen ID
0      KG11N     KG11N       HTA8_6001    HTA8_6001_001101
1      KG11P     KG11P       HTA8_6001    HTA8_6001_002101
2     KG11Li     KG11M       HTA8_6001    HTA8_6001_003101
3      KG20N     KG20N       HTA8_6002    HTA8_6002_001101
4      KG20P     KG20P       HTA8_6002    HTA8_6002_002101
..       ...       ...             ...                 ...
85    KG11Li    KG117M             NaN                 NaN
86    KG138N    KG138N             NaN                 NaN
87    KG138P    KG138P             NaN                 NaN
88   KG181Li    KG181M             NaN                 NaN
89  KG183NLi  KG283NLi             NaN                 NaN

[90 rows x 4 columns]

In [38]:
df_reduce_file_patient = df_file_patient[[ 'Filename','Biospecimen', 'HTAN Data File ID', 'Synapse Id']]

df_merge_info_patient = pd.merge(df_reduce_ID_patient, df_reduce_file_patient,
                    left_on='HTAN Biospecimen ID',  right_on='Biospecimen',
                    how='left')
                    

print(df_merge_info_patient.head())

  Lab ID  H5AD ID HTAN Patient ID HTAN Biospecimen ID  \
0   KG11N   KG11N       HTA8_6001    HTA8_6001_001101
1   KG11N   KG11N       HTA8_6001    HTA8_6001_001101
2   KG11N   KG11N       HTA8_6001    HTA8_6001_001101
3   KG11N   KG11N       HTA8_6001    HTA8_6001_001101
4   KG11P   KG11P       HTA8_6001    HTA8_6001_002101

                                            Filename       Biospecimen  \
0  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_001101
1  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_001101
2  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_001101
3  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_001101
4  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_002101

     HTAN Data File ID   Synapse Id
0  HTA8_6001_001101006  syn61371036
1  HTA8_6001_001101009  syn61370828
2  HTA8_6001_001101007  syn61371037
3  HTA8_6001_001101008  syn61371038
4  HTA8_6001_002101006  syn61371041

In [40]:
df_merge_info_patient[df_merge_info_patient.isna().any(axis=1)]

,Lab ID,H5AD ID,HTAN Patient ID,HTAN Biospecimen ID,Filename,Biospecimen,HTAN Data File ID,Synapse Id
332,KG117N,KG117N,NaN,NaN,NaN,NaN,NaN,NaN
333,KG117P,KG117P,NaN,NaN,NaN,NaN,NaN,NaN
334,KG11Li,KG117M,NaN,NaN,NaN,NaN,NaN,NaN
335,KG138N,KG138N,NaN,NaN,NaN,NaN,NaN,NaN
336,KG138P,KG138P,NaN,NaN,NaN,NaN,NaN,NaN
337,KG181Li,KG181M,NaN,NaN,NaN,NaN,NaN,NaN
338,KG183NLi,KG283NLi,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df_merge_info_patient.dropna(inplace=True)

print(f"Numero di righe: {df_merge_info_patient.shape[0]}")

Numero di righe: 332

In [42]:
print(df_merge_info_patient['Filename'].str.endswith('.mtx').sum())

83

In [43]:
df_mtx_files_patient = df_merge_info_patient[df_merge_info_patient['Filename'].str.endswith('.mtx') & df_merge_info_patient['Lab ID '].str.contains('Li(.$)?$', regex=True)]
print(df_mtx_files_patient)
num_row_mtx = df_mtx_files_patient.shape[0]
print(f"Numero di righe: {num_row_mtx}")

      Lab ID   H5AD ID HTAN Patient ID HTAN Biospecimen ID  \
10     KG11Li    KG11M       HTA8_6001    HTA8_6001_003101
22     KG20Li    KG20M       HTA8_6002    HTA8_6002_003101
30     KG35Li    KG35M       HTA8_6003    HTA8_6003_002101
34     KG39Li    KG39M       HTA8_6004    HTA8_6004_001101
42     KG60Li    KG60M       HTA8_6005    HTA8_6005_002101
54     KG66Li    KG66M       HTA8_6006    HTA8_6006_003101
70     KG70Li    KG70M       HTA8_6007    HTA8_6007_003101
78     KG71Li    KG71M       HTA8_6008    HTA8_6008_002101
90     KG74Li    KG74M       HTA8_6009    HTA8_6009_003101
102   KG75Li     KG75M       HTA8_6010    HTA8_6010_003101
106   KG75Li2   KG75M2       HTA8_6010    HTA8_6010_004101
118    KG79Li    KG79M       HTA8_6011    HTA8_6011_003101
126    KG82Li    KG82M       HTA8_6012    HTA8_6012_002101
130   KG82Li2   KG82M2       HTA8_6012    HTA8_6012_003101
142   KG103Li   KG103M       HTA8_6013    HTA8_6013_003101
150   KG105Li   KG105M       HTA8_6014    HTA8_6014_002101
158   KG119Li   KG119M       HTA8_6015    HTA8_6015_002101
170   KG136Li   KG136M       HTA8_6016    HTA8_6016_003101
182   KG146Li   KG146M       HTA8_6017    HTA8_6017_003101
198   KG150Li   KG150M       HTA8_6018    HTA8_6018_003101
210   KG151Li   KG151M       HTA8_6019    HTA8_6019_003101
222   KG156Li   KG156M       HTA8_6020    HTA8_6020_003101
242   KG182Li   KG182M       HTA8_6022    HTA8_6022_003101
258   KG183Li   KG183M       HTA8_6023    HTA8_6023_003101
262  KG183Li2  KG183M2       HTA8_6023    HTA8_6023_004101
274   KG184Li   KG184M       HTA8_6024    HTA8_6024_003101
286   KG188Li   KG188M       HTA8_6025    HTA8_6025_003101
298   KG190Li   KG190M       HTA8_6026    HTA8_6026_003101
310  KG194Li2   KG194M       HTA8_6027    HTA8_6027_003101
322   KG183Li   KG283M       HTA8_6028    HTA8_6028_003101

                                              Filename       Biospecimen  \
10   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6001_003101
22   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6002_003101
30   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6003_002101
34   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6004_001101
42   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6005_002101
54   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6006_003101
70   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6007_003101
78   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6008_002101
90   moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6009_003101
102  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6010_003101
106  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6010_004101
118  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6011_003101
126  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6012_002101
130  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6012_003101
142  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6013_003101
150  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6014_002101
158  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6015_002101
170  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6016_003101
182  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6017_003101
198  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6018_003101
210  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6019_003101
222  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6020_003101
242  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6022_003101
258  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6023_003101
262  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6023_004101
274  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6024_003101
286  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6025_003101
298  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6026_003101
310  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6027_003101
322  moorman_etal_single_cell_RNAseq_level_3/HTA8_6...  HTA8_6028_003101

       HTAN Data File ID   Synapse Id
10   HTA8_6001_003101007  syn61371164
22   HTA8_6002_003101007  syn61371180
30   HTA8_6003_002101007  syn61371192
34   HTA8_6004_001101007  syn61371198
42   HTA8_6005_002101005  syn61371206
54   HTA8_6006_003101007  syn61371226
70   HTA8_6007_003101007  syn61371269
78   HTA8_6008_002101007  syn61371288
90   HTA8_6009_003101007  syn61371309
102  HTA8_6010_003101007  syn61371332
106  HTA8_6010_004101007  syn61371337
118  HTA8_6011_003101007  syn61371386
126  HTA8_6012_002101006  syn61371423
130  HTA8_6012_003101006  syn61371441
142  HTA8_6013_003101004  syn61371498
150  HTA8_6014_002101004  syn61371553
158  HTA8_6015_002101007  syn61371593
170  HTA8_6016_003101005  syn61371650
182  HTA8_6017_003101011  syn61371705
198  HTA8_6018_003101011  syn61371784
210  HTA8_6019_003101011  syn61371839
222  HTA8_6020_003101011  syn61371889
242  HTA8_6022_003101005  syn61371979
258  HTA8_6023_003101005  syn61372037
262  HTA8_6023_004101005  syn61372052
274  HTA8_6024_003101005  syn61372089
286  HTA8_6025_003101004  syn61372152
298  HTA8_6026_003101011  syn61372216
310  HTA8_6027_003101011  syn61372263
322  HTA8_6028_003101011  syn61372320
Numero di righe: 30

/tmp/ipykernel_965702/3609430165.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_mtx_files_patient = df_merge_info_patient[df_merge_info_patient['Filename'].str.endswith('.mtx') & df_merge_info_patient['Lab ID '].str.contains('Li(.$)?$', regex=True)]

In [ ]:
# Estrai il Synapse ID (assumendo che sia in una colonna chiamata 'synapse_id')
df_synapse_ID = df_mtx_files_patient[['Lab ID ','Synapse Id']]

      Lab ID    Synapse Id
10     KG11Li  syn61371164
22     KG20Li  syn61371180
30     KG35Li  syn61371192
34     KG39Li  syn61371198
42     KG60Li  syn61371206
54     KG66Li  syn61371226
70     KG70Li  syn61371269
78     KG71Li  syn61371288
90     KG74Li  syn61371309
102   KG75Li   syn61371332
106   KG75Li2  syn61371337
118    KG79Li  syn61371386
126    KG82Li  syn61371423
130   KG82Li2  syn61371441
142   KG103Li  syn61371498
150   KG105Li  syn61371553
158   KG119Li  syn61371593
170   KG136Li  syn61371650
182   KG146Li  syn61371705
198   KG150Li  syn61371784
210   KG151Li  syn61371839
222   KG156Li  syn61371889
242   KG182Li  syn61371979
258   KG183Li  syn61372037
262  KG183Li2  syn61372052
274   KG184Li  syn61372089
286   KG188Li  syn61372152
298   KG190Li  syn61372216
310  KG194Li2  syn61372263
322   KG183Li  syn61372320

In [1]:
#step finale: scaricare i file mtx da synapse
import synapseclient 
syn = synapseclient.Synapse()

# OR using an access token
syn.login(authToken='eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZy9hdXRoL3YxIiwiYXVkIjoiMCIsIm5iZiI6MTc0MzY5MTYwMSwiaWF0IjoxNzQzNjkxNjAxLCJqdGkiOiIxODU2MSIsInN1YiI6IjM1Mzc2NjAifQ.POTZ-j04NG-7D8e2snE9qX_K_98TU8zzK8lkM-5uaQGA6Qq7cvLjPgEs1WOjyY2kraCrL81PaG-qLc3aIWlBOCLCnRYVuTdhgulPdD447Wc_nre738YvVyUYSJAWymalvhta8X6L97ZrB0C0gUhF-eTlh5MuAXi_uwsYqPRKTWwmdUUfnDTq9jR-CyX-6ipKkl74pBNYDi0lyYjgLmoKs8N-rp_brQzZVkBpf12xyL_M1lAkQtIgIGkp_sZ8HCqSDUfSaqGYMlEn1kDO4UIOK5vqJomgAR8GblKH7yRAjOw3KoA-_5XtQye1oMZn87BScRYOoHAmNeMkgi-e7HnKXg')

ModuleNotFoundError: No module named 'synapseclient'

In [ ]:
for synapseID in synapse_id[:3]:
    entity = syn.get(synapseID, downloadLocation="synapse_mtx")

'for synapseID in synapse_id[:3]:\n    entity = syn.get(synapseID, downloadLocation="/Users/gae/Documents/univeristà/unito/Thesis/Progressive plasticity during colorectal cancer metastasis/synapse_mtx")\n'