In [2]:
library(reshape)
library(ez)

d <- read.table('~/ANOVA_DLL1.tsv', sep='\t', header=TRUE, stringsAsFactors = FALSE)
colnames(d) <- gsub('(\\w+)(\\d)', "\\1_\\2", colnames(d))
longf <- melt(d, id.vars="time")
longf$variable <- as.character(longf$variable)
longf$treat <- sapply(strsplit(longf$variable, '_'), function(x){x[[1]][1]})
longf$replicate <- sapply(strsplit(longf$variable, '_'), function(x){x[[2]][1]})

longf$treat <- as.factor(longf$treat)
longf$replicate <- as.factor(longf$replicate)
longf$time <- as.factor(longf$time)

In [8]:
#https://stats.stackexchange.com/questions/23305/why-is-ezanova-not-giving-me-mauchly%C2%B4s-test-of-sphericity-even-though-i-belive
ezANOVA(data    = longf, 
        wid     = replicate, 
        within  = .(treat, time),
        dv      = value, type=2)

$ANOVA
      Effect DFn DFd        F            p p<.05        ges
2      treat   1   2 76.86122 1.276194e-02     * 0.59083680
3       time   6  12 36.67005 4.894677e-07     * 0.40186504
4 treat:time   6  12 10.48402 3.524857e-04     * 0.06296283

$`Mauchly's Test for Sphericity`
      Effect            W p p<.05
3       time 4.319776e-62 1
4 treat:time 2.698065e-59 1

$`Sphericity Corrections`
      Effect       GGe      p[GG] p[GG]<.05       HFe      p[HF] p[HF]<.05
3       time 0.1734661 0.02380693         * 0.1950212 0.01760225         *
4 treat:time 0.1784503 0.07661459           0.2173873 0.05771863

In [3]:
# nono, chiaramente
ezANOVA(data    = longf, 
        wid     = replicate, 
        between  = .(treat, time),
        dv      = value)

Warning message:
“The column supplied as the wid variable contains non-unique values across levels of the supplied between-Ss variables. Automatically fixing this by generating unique wid labels.”
Coefficient covariances computed by hccm()

$ANOVA
      Effect DFn DFd          F            p p<.05        ges
1      treat   1  28 40.4323516 7.010767e-07     * 0.59083680
2       time   6  28  3.1353630 1.769254e-02     * 0.40186504
3 treat:time   6  28  0.3135698 9.244747e-01       0.06296283

$`Levene's Test for Homogeneity of Variance`
  DFn DFd      SSn      SSd         F         p p<.05
1  13  28 2.215484 43.76117 0.1090421 0.9999266

In [16]:

ezANOVA(data    = longf, 
        wid = replicate,
        within_full = treat,
        within = time,
        dv      = value)

Warning message:
“Collapsing data to cell means first using variables supplied to "within_full", then collapsing the resulting means to means for the cells supplied to "within".”

Error in lambda > 0 : invalid comparison with complex values

ERROR: Error in ezANOVA_main(data = data, dv = dv, wid = wid, within = within, : The car::Anova() function used to compute results and assumption tests seems to have failed. Most commonly this is because you have too few subjects relative to the number of cells in the within-Ss design. It is possible that trying the ANOVA again with "type=1" may yield results (but definitely no assumption tests).